/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all files that contain Nativewind classes.
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        backgroundLight: "#F2F2F2",
        backgroundDark: "#1C1C27",
        primary: "#7453F9",
        cardDark: "#2B2A3A",
        cardLigth: "#fff",
        tabsDark: "#2B2B38",
        tabsLigth: "#FAFBFC",
        // emAndamento: "#094BAC",
        emAndamento: "#1D4ED8",
        // emAndamentoCard: "#A9C0E2",
        emAndamentoCard: "#DBEAFE",
        // emAndamentoCardDark: "#1E2A4A",
        emAndamentoCardDark: "#202737",
        atrasada: "#FF5757",
        atrasadaCard: "#FEE2E2",
        // atrasadaCardDark: "#3A1E1E",
        atrasadaCardDark: "#451A1D",
        // concluida: "#34AF68",
        concluida: "#22C55E",
        // concluidaCard: "#bfebd2",
        concluidaCard: "#DCFCE7",
        // concluidaCardDark: "#1E3A2A",
        concluidaCardDark: "#1E2D27",
        pendente: "#E4B926",
        // pendenteCard: "#FFF2C5",
        pendenteCard: "#FEF3C7",
        // pendenteCardDark: "#3A371E",
        pendenteCardDark: "#31291E",
      },
      fontFamily: {
        regular: "Inter_400Regular",
        medium: "Poppins_500Medium",
        semibold: "Inter_600SemiBold",
        poppins_bold: "Inter_700Bold",
      },
    },
  },
  plugins: [],
};
